App:
  Port : 8088  # 应用端口号
  
Database:
  Name: go-chain  #数据库名称
  Host: 127.0.0.1 #数据库链接，如 127.0.0.1:3306
  Port: 3306 #数据库端口号
  Username: root #用户名
  Password: 123456 #数据库密码

Redis:
  Host: 127.0.0.1
  Port: 6379
  Password:
  Db: 0
  PoolSize: 10  #连接池大小

BlockChain:
  RpcUrl: https://sepolia.infura.io/v3/{key}
    #  区块链rpc地址  infura.io 可以获取
  WssUrl: #wss://sepolia.infura.io/ws/v3/{key}
  #区块链wss地址
  NftAuctionContract: 0x9a22E86A2Db8AbD5bF3aD302d73735F87510ACF9
  NftAuctionStartBlock: 9975036
  NftContract: 0xb834404C86987E297b074C7b4C148368E64F8d7C
  NftStartBlock: 9975260  #起始区块号，默认为合约创建时间

Jwt:
  Secret: go-chain  #jwt密钥